openapi: 3.0.0
info:
  title: Nuxt OSS API
  description: API untuk menampilkan informasi wilayah di Indonesia.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server
